name: "Basic Container Action"
description: "Does something vague"
author: "spriceware"

inputs:
  TEST_DROID:
    description: "Testing Droid"
    required: true
    default: "roboTest"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "blue"
