name: A workflow for a Basic Action
on: push

jobs:
  build:
    name: Basic on-push action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          TEST_DROID: "spricewareTesting"
