name: A workflow for a Basic Action
on: push

jobs:
  build:
    name: Basic on-push action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          TEST_DROID: "spricewareTesting"

  basic_js_action_job: 
    name: "A basic JS action job"
    runs-on: ubuntu-latest
    steps: 
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        id: jsaction
        name: "Basic JS action step"
        uses: ./action-b
        with: 
          originator: spriceware
      - 
        name: "Get the action output time"
        run: echo "The time was ${{ steps.jsaction.outputs.time }}"
